### ISSUE TITLE
CodeMirror double click to select word doesn't handle Suneido's trailing ! and ?

### ISSUE THREAD

**Issue by apmckinlay** [apmckinlay/suneido.js#10]
Ctrl+left and Ctrl-right also have this issue.

I can't find anywhere in the CodeMirror settings to define what "word characters" are.

I guess we could write our own functions for select/skip word but it seems like there should be a way to configure this.

**Comment by xiehaom7** [comment]
In codemirror.js, the method findWordAt is used to find the  word when double clicked. This function uses the method isWordChar to judge if the adjacent char should be included into the word or not. Within that function, Code "/\w/.test(ch)" is used. Change this into "/[\w?!]/.test(ch)" will make double click select ! and ? into the word, as well as Ctrl+shift+left and right. 

Not sure if changing the codemirror.js file is a good idea. From the code, it seems defining a helper is an option. I will look into that.

Also tried to register a handler to the "dblclick" event, but there are two issues:
1. the handler not be triggered every time
2. the word without ! or ? was first selected, Than, after a  noticeable delay, the whole word was selected (what my code did).

**Comment by apmckinlay** [comment]
Maybe we could modify the code so the regular expression could be specified with an option. Then we could see if CodeMirror would accept a pull request.

**Comment by xiehaom7** [comment]
Defining a helper with "wordChars" type in CodeMirror could override the original setting. Just add one line code in our mode suneido.js file:
     CodeMirror.registerHelper("wordChars", "suneido", /[\w?!]/);
The demo file javascript.js used it in the same way.

**Comment by apmckinlay** [comment]
This is done
