### ISSUE TITLE
implement Suneido regular expressions

### ISSUE THREAD

**Issue by apmckinlay** [apmckinlay/suneido.js#19]
copy the jSuneido Java implementation

CharMatcher is already implemented

once this is done, convert strings.ts to use it

**Comment by xiehaom7** [comment]
Submitted a pull request for this.

In addition, notice that the JSuneido's StringMethod implementation has two places which are inconsistent with the documentation.

1. In the String's replace method, argument count = 0 will still cause one replacement;
2. In the String's replace method, \u and \l are treated as \U and \I.

Fixed these two problems in the submitted Suneido.js code.

**Comment by apmckinlay** [comment]
Sounds good, thanks Hao

**Comment by apmckinlay** [comment]
Missed closing this.
