### ISSUE TITLE
Name clash on "require"

### ISSUE THREAD

**Issue by lcreid** [apmckinlay/suneido.js#2]
With version 1.5 of TypeScript, there's a name clash on the symbol "require" from `require.js`. Stackoverflow has a question about it [here](http://stackoverflow.com/questions/21380588/conflict-between-requirejs-and-nodejs-definitions-in-typescript).

@apmckinlay suggested just making `play.ts` into a regular JavaScript tile, since that's where the requires are.

**Comment by apmckinlay** [comment]
changed play.ts to play.js
