### ISSUE TITLE
improve libview.html so that back/forwards/bookmarks work

### ISSUE THREAD

**Issue by apmckinlay** [apmckinlay/suneido.js#7]
I think this would mean that load would change the url to have the name on the end
e.g. libview.html#Name

And then you'd need something so when a url was loaded with a name on the end it would do the load

**Comment by lcreid** [comment]
Just a quick thought on this: I think this is where people start using front-end frameworks. They help solve the "back button problem" for apps with significant JavaScript, which is almost everything these days. 
On 12 Jun 2015 1:07 pm, Andrew McKinlay <notifications@github.com> wrote:I think this would mean that load would change the url to have the name on the end
e.g. libview.html#Name

And then you'd need something so when a url was loaded with a name on the end it would do the load

**Comment by apmckinlay** [comment]
Since we haven't chosen/tried any frameworks yet, and I wanted to have an idea how this worked anyway, I hacked together something with push/pop state. Required a minor change to JsPlayServer to  handle when the user reloads a url. I'm not sure what the "normal" solution is, but the way I handled it the server returns the same basic page for both /libview.html and for /libview.html/Name and the browser side detects where there's a name on the url and then loads it. Alternately you could have the server return the page with the appropriate content but that's a little harder.

I will close this for now since it's working (I think). Once we get into frameworks we'll probably want to redo it.
